remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: React Coolicons viewer
description: Easy to use React coolicons library as react components.